### ISSUE TITLE
Can't find chat box

### ISSUE THREAD

**Issue by RyanH3103** [Raphire/SusAlert#10]
I've had the client before but not since the Jagex Launcher.

I have installed it as I did befor but it just sits there flashing "Can't find chat box" and then times out to say can't find RS Client

Any help...

I have all the settings as required

**Comment by RyanH3103** [comment]
![Uploading Screenshot 2023-12-16 171143.png…]()

**Comment by Raphire** [comment]
Heya, 

Unfortunately I can't see your screenshot, but I have encountered this issue personally in the past. Could you try these steps:
- Fully close alt1
- Open RS, keep the window focussed
- Open alt1 and make sure the alt1 menu is visible in the top right of the RS client.
- Now open SusAlert, it should find the RS client now

Let me know if this works for ya.

**Comment by RyanH3103** [comment]
No this hasn't fixed it at all.

I've tried uninstalling Alt1 and reinstalling it. This hasn't fixed it either.

When I open sus alert, i get a pop up saying that the capture has changed to OpenGL

**Comment by Raphire** [comment]
Do you have this issue with other alt1 apps that use the screen? Because this sounds like an issue with alt1 not being able to find your RS window. SusAlert relies on alt1 to capture the screen. This issue could be due to a variety of reasons, alt1 has an FAQ here: https://runeapps.org/help_alt1_capture

Please check in the alt1 settings if alt1 sees the runescape window:
- Press 'Alt1 Toolkit' in the top right
- Next go to 'Settings'
- And then go to the 'Capture' tab in the settings window

This will look something like this;
![image](https://github.com/Raphire/SusAlert/assets/9938813/f5c06822-0684-47ae-809e-71b540c9de66)

You should see a (moving) preview window of your rs client in the bottom right, with a message in the bottom left whether or not it seems to work correctly or not. If alt1 does indeed have issues then you can try to change the capture mode, otherwise I'm afraid you'll have to ask for help on the [alt1 forums](https://runeapps.org/forums/index.php).
