### ISSUE TITLE
Stuck at looking for chatbox

### ISSUE THREAD

**Issue by WildFearless** [Raphire/SusAlert#5]
Its just stuck, i was on steam client, tried on vanilla client and doesnt work. Im using a pre release version so i dont have a choice to use the alt1 browser because alt1:://url wont work since its not installed on my pc, prerelease are just the files in a zip

**Comment by Raphire** [comment]
Hey, I saw in your post on the runeapps forum that the issue is already resolved. 

For future reference the issue occurs due to the fact that susalert does not have permissions to view the screen when it's launched in the browser. You have to add it as an app to alt1 and give the required permissions. I'll see if I can add a clear error message as currently it'll just get stuck on looking for chatbox.
