### ISSUE TITLE
Randomly resetting to beginning of kill.

### ISSUE THREAD

**Issue by txj-xyz** [Raphire/SusAlert#6]
Hi, it appears that the module is resetting itself at random times throughout the kill back to beginning of the kill, is there something that I should be checking or fixing?

It appears to be reading everything just fine, however randomly without moving anything the kill will reset in the tracker.

**Comment by Raphire** [comment]
Heya, SusAlert uses the bosstimer to determine when the bossfight starts and ends. It's possible that you may accidentally stop and restart the fight mid-kill if you obstruct the bosstimer (with mouse cursor or a tooltip for example) for longer than about 1.5 seconds. 

Do you have your bosstimer in a position where it may be obstructed by other interface elements or your cursor? If so you can try moving the bosstimer to see if that resolves things. I will see if I can make the behaviour of this a bit smarter and less prone to this issue in a future update.

Thanks!

**Comment by txj-xyz** [comment]
Thank you brother, I shall give those a shot :) Closing.

**Comment by Raphire** [comment]
Quick update as I finally had the time to look into this issue more: There was actually issue that could cause the timer to reset mid-kill even if the timer was only obstructed for periods shorter than 3 ticks, because a variable wasn't being reset properly. This has now been fixed and in addition it now requires 4 ticks (2.4 seconds) of not detecting a bosstimer before SusAlert ends the timer.
